# Generated by Django 2.0.2 on 2018-08-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnSiteOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb', models.TextField(max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('unit_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('remuneration', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('multiplier', models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True)),
                ('agreement_term', models.IntegerField(default=0, null=True)),
                ('agreement_remain', models.IntegerField(default=0, null=True)),
                ('agreement_age', models.IntegerField(default=0, null=True)),
                ('total_unit', models.IntegerField(default=0, null=True)),
                ('wage_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('owner_occupy', models.IntegerField(default=0, null=True)),
                ('letting', models.IntegerField(default=0, null=True)),
                ('income_per_letting', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('look_ups', models.IntegerField(default=0, null=True)),
                ('outside_agents', models.IntegerField(default=0, null=True)),
                ('manager_bed', models.IntegerField(default=0, null=True)),
                ('manager_bathroom', models.IntegerField(default=0, null=True)),
                ('manager_car', models.IntegerField(default=0, null=True)),
                ('office', models.IntegerField(default=0, null=True)),
                ('office_hour', models.IntegerField(default=0, null=True)),
                ('agency', models.TextField(max_length=50, null=True)),
                ('agent', models.TextField(max_length=50, null=True)),
                ('complex_feature', models.TextField(max_length=500, null=True)),
                ('url', models.TextField(max_length=100, null=True)),
                ('title', models.TextField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('unit_feature', models.TextField(max_length=500, null=True)),
                ('pets', models.TextField(max_length=50, null=True)),
                ('last_update', models.TextField(max_length=100, null=True)),
                ('property_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Onsiteweb_Origin_info',
                'ordering': ('suburb',),
            },
        ),
    ]
