# Generated by Django 2.0.2 on 2018-09-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField()),
                ('crawl_date', models.DateField()),
                ('street_address', models.TextField(max_length=100, null=True)),
                ('suburb', models.TextField(max_length=50, null=True)),
                ('post_code', models.TextField(max_length=50, null=True)),
                ('bed', models.IntegerField(default=0, null=True)),
                ('bathroom', models.IntegerField(default=0, null=True)),
                ('car', models.IntegerField(default=0, null=True)),
                ('property_type', models.TextField(max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('price_des', models.TextField(max_length=50, null=True)),
                ('date_available', models.TextField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('bond', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('allowance', models.TextField(max_length=100, null=True)),
                ('indoor_feature', models.TextField(max_length=500, null=True)),
                ('outdoor_feature', models.TextField(max_length=500, null=True)),
                ('other_feature', models.TextField(max_length=500, null=True)),
                ('floorplan', models.TextField(max_length=500, null=True)),
                ('school', models.TextField(null=True)),
                ('median_rent', models.TextField(max_length=200, null=True)),
                ('rental_yield', models.TextField(max_length=200, null=True)),
                ('agency', models.TextField(max_length=200, null=True)),
                ('agent', models.TextField(max_length=200, null=True)),
                ('url', models.TextField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Realestate_Rent_Origin_info',
                'ordering': ('suburb',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='rentorigin',
            unique_together={('property_id', 'crawl_date')},
        ),
    ]
